config/routes.rb
module EntityMaintenance
  Engine.routes.draw do
    resources :entities do
      resources :addresses, :only => [:new, :edit, :create, :update, :destroy]
      resources :contact_infos, :only => [:new, :edit, :create, :update, :destroy]
    end

    namespace :api do
      resources :people, :only => [:index, :show]
      resources :organizations, :only => [:index, :show]
    end
  end
end

app/models/entity_maintenance/address.rb
module EntityMaintenance
  class Address < ActiveRecord::Base
    belongs_to :entity
    validates :line_1, :city, :province_or_state, :country, :zipcode, :presence => true

    def street_address
      "#{line_1} #{line_2 ? line_2 : ''}".strip
    end
  end
end

app/models/entity_maintenance/contact_info.rb
module EntityMaintenance
  class ContactInfo < ActiveRecord::Base
    belongs_to :entity

    validates :contact_type, :contact_number, :presence => true
  end
end

app/models/entity_maintenance/entity.rb
module EntityMaintenance
  class Entity < ActiveRecord::Base
    has_many :addresses
    has_many :contact_infos
  end
end

app/models/entity_maintenance/organization.rb
module EntityMaintenance
  class Organization < Entity
    validates :name, :presence => true
    validates :name, :uniqueness => true
  end
end

app/models/entity_maintenance/person.rb
module EntityMaintenance
  class Person < Entity
    validates :first_name, :last_name, :prefix, :presence => true

    def full_name
      "#{prefix} #{first_name} #{middle_name ? middle_name : ''} #{last_name}".strip
    end
  end
end

app/controllers/entity_maintenance/addresses_controller.rb
module EntityMaintenance
  class AddressesController < EntityMaintenance::ApplicationController
    before_action :set_entity, :only => [:new, :create, :edit, :update, :destroy]
    before_action :set_address, :only => [:edit, :update, :destroy]

    def new
      @entity = Entity.find(params[:entity_id])
      @address = Address.new(:entity => @entity)
      puts @address
    end

    def create
      @address = Address.new(address_params)

      if @address.save
        redirect_to entity_path(@entity), :notice => 'Address was successfully created.'
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @address.update(address_params)
        redirect_to entity_path(@entity), :notice => 'Address was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @address.destroy
      redirect_to entity_path(@entity), :notice => 'Address was successfully destroyed.'
    end

    private

    def set_address
      @address = Address.find(params[:id])
    end

    def set_entity
      @entity = Entity.find(params[:entity_id])
    end

    def address_params
      params.require(:address).permit(:line_1,
                                      :line_2,
                                      :city,
                                      :province_or_state,
                                      :country,
                                      :zipcode,
                                      :entity_id)
    end
  end
end

app/controllers/entity_maintenance/api/organizations_controller.rb
module EntityMaintenance
  class Api::OrganizationsController < EntityMaintenance::ApplicationController
    def index
      @organizations = Organization.order(:name)
    end

    def show
      @organization = Organization.find(params[:id])
    end
  end
end

app/controllers/entity_maintenance/api/people_controller.rb
module EntityMaintenance
  class Api::PeopleController < EntityMaintenance::ApplicationController
    def index
      @people = Person.order(:last_name)
    end

    def show
      @person = Person.find(params[:id])
    end
  end
end

app/controllers/entity_maintenance/application_controller.rb
module EntityMaintenance
  class ApplicationController < ActionController::Base
  end
end

app/controllers/entity_maintenance/contact_infos_controller.rb
module EntityMaintenance
  class ContactInfosController < EntityMaintenance::ApplicationController
    before_action :set_entity, :only => [:new, :create, :edit, :update, :destroy]
    before_action :set_contact_info, :only => [:edit, :update, :destroy]

    def new
      @entity = Entity.find(params[:entity_id])
      @contact_info = ContactInfo.new(:entity => @entity)
      puts @contact_info
    end

    def create
      @contact_info = ContactInfo.new(contact_info_params)

      if @contact_info.save
        redirect_to entity_path(@entity), :notice => 'Contact Info was successfully created.'
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @contact_info.update(contact_info_params)
        redirect_to entity_path(@entity), :notice => 'Contact Info was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @contact_info.destroy
      redirect_to entity_path(@entity), :notice => 'Contact Info was successfully destroyed.'
    end

    private

    def set_contact_info
      @contact_info = ContactInfo.find(params[:id])
    end

    def set_entity
      @entity = Entity.find(params[:entity_id])
    end

    def contact_info_params
      params.require(:contact_info).permit(:contact_person,
                                           :contact_number,
                                           :contact_type,
                                           :entity_id)
    end
  end
end

app/controllers/entity_maintenance/entities_controller.rb
module EntityMaintenance
  class EntitiesController < EntityMaintenance::ApplicationController
    before_action :set_entity, :only => [:show, :edit, :update, :destroy]

    # GET /entities
    def index
      @people = Person.order(:last_name)
      @orgs = Organization.order(:name)
    end

    # GET /entities/1
    def show
    end

    # GET /entities/new
    def new
      @entity = Entity.new
      @entity.type = params[:type] if params[:type].present?
    end

    # GET /entities/1/edit
    def edit
    end

    # POST /entities
    def create
      @entity = Entity.new(entity_params)

      if @entity.save
        redirect_to entity_path(@entity), :notice => 'Entity was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /entities/1
    def update
      if @entity.class == EntityMaintenance::Person && @entity.update(person_params)
        redirect_to entity_path(@entity), :notice => 'Person was successfully updated.'
      elsif @entity.class == EntityMaintenance::Organization && @entity.update(organization_params)
        redirect_to entity_path(@entity), :notice => 'Organization was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /entities/1
    def destroy
      @entity.destroy
      redirect_to entities_url, :notice => 'Entity was successfully destroyed.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_entity
      @entity = Entity.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def entity_params
      params.require(:entity).permit(:first_name,
                                     :middle_name,
                                     :last_name,
                                     :prefix,
                                     :name,
                                     :industry,
                                     :type)
    end

    def person_params
      params.require(:person).permit(:first_name,
                                     :middle_name,
                                     :last_name,
                                     :prefix,
                                     :type)
    end

    def organization_params
      params.require(:organization).permit(:name,
                                           :industry,
                                           :type)
    end
  end
end

app/helpers/entity_maintenance/application_helper.rb
module EntityMaintenance
  module ApplicationHelper
  end
end

app/views/entity_maintenance/addresses/_form.html.haml
= form.input :line_1
= form.input :line_2
= form.input :city
= form.input :province_or_state
= form.input :country
= form.input :zipcode
= form.input :entity_id, :as => :hidden

= form.button :submit
\|
= link_to 'Cancel', cancel_url

app/views/entity_maintenance/addresses/_table.html.haml
%table
  %thead
    %tr
      %th Address
      %th City
      %th Province Or State
      %th Country
      %th Zipcode
      %th Actions
  %tbody
    - entity.addresses.each do |address|
      %tr
        %td= address.street_address
        %td= address.city
        %td= address.province_or_state
        %td= address.country
        %td= address.zipcode
        %td
          = link_to "Edit", edit_entity_address_path(entity, address)
          \|
          = link_to 'Destroy', entity_address_path(entity, address), :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/entity_maintenance/addresses/edit.html.haml
%h1 Editing Address

= simple_form_for @address, :url => entity_address_path(@entity, @address), :html => { :class => 'form' } do |form|
  = render 'form', :form => form, :cancel_url => entity_path(@entity)

app/views/entity_maintenance/addresses/new.html.haml
%h1
  = "New address for #{@entity.class == EntityMaintenance::Person ? @entity.full_name : @entity.name}"

= simple_form_for @address, :url => entity_addresses_path(@entity), :html => { :class => 'form' } do |form|
  = render 'form', :form => form, :cancel_url => entity_path(@entity)

app/views/entity_maintenance/contact_infos/_form.html.haml
- if entity.class == EntityMaintenance::Organization
  = form.input :contact_person
= form.input :contact_number
= form.input :contact_type
= form.input :entity_id, :as => :hidden

= form.button :submit
\|
= link_to 'Cancel', cancel_url

app/views/entity_maintenance/contact_infos/_table.html.haml
%table
  %thead
    %tr
      - if @entity.class == EntityMaintenance::Organization
        %th Person
      %th Number
      %th Type
      %th Actions
  %tbody
    - entity.contact_infos.each do |contact_info|
      %tr
        - if @entity.class == EntityMaintenance::Organization
          %td= contact_info.contact_person
        %td= contact_info.contact_number
        %td= contact_info.contact_type
        %td
          = link_to "Edit", edit_entity_contact_info_path(entity, contact_info)
          \|
          = link_to 'Destroy', entity_contact_info_path(entity, contact_info), :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/entity_maintenance/contact_infos/edit.html.haml
%h1 Editing Contact Info

= simple_form_for @contact_info, :url => entity_contact_info_path(@entity, @contact_info), :html => { :class => 'form' } do |form|
  = render 'form', :form => form, :entity => @entity, :cancel_url => entity_path(@entity)

app/views/entity_maintenance/contact_infos/new.html.haml
%h1
  = "New contact info for #{@entity.class == EntityMaintenance::Person ? @entity.full_name : @entity.name}"

= simple_form_for @contact_info, :url => entity_contact_infos_path(@entity), :html => { :class => 'form' } do |form|
  = render 'form', :form => form, :entity => @entity, :cancel_url => entity_path(@entity)

app/views/entity_maintenance/entities/_form.html.haml
= form_for @entity do |f|
  - if @entity.errors.any?
    #error_explanation
      %h2= "#{pluralize(@entity.errors.count, "error")} prohibited this entity from being saved:"
      %ul
        - @entity.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/entity_maintenance/entities/_organization_form.html.haml
= form.input :name, :required => true
= form.input :industry
= form.input :type, :as => :hidden

= form.button :submit
\|
= link_to 'Cancel', cancel_url

app/views/entity_maintenance/entities/_organizations.html.haml
%table
  %thead
    %tr
      %th Name
      %th Industry
  %tbody
    - @orgs.each do |org|
      %tr
        %td= link_to org.name, entity_path(org)
        %td= org.industry

app/views/entity_maintenance/entities/_people.html.haml
%table
  %thead
    %tr
      %th Last Name
      %th First Name
      %th Middle Name
      %th Prefix
  %tbody
    - @people.each do |person|
      %tr
        %td= link_to person.last_name, entity_path(person)
        %td= person.first_name
        %td= person.middle_name
        %td= person.prefix

app/views/entity_maintenance/entities/_person_form.html.haml
= form.input :prefix, :required => true
= form.input :first_name, :required => true
= form.input :middle_name
= form.input :last_name, :required => true
= form.input :type, :as => :hidden

= form.button :submit
\|
= link_to 'Cancel', cancel_url

app/views/entity_maintenance/entities/edit.html.haml
%h1 Editing entity

= simple_form_for @entity, :url => entity_path(@entity), :html => { :class => 'form' } do |form|
  - if @entity.type == EntityMaintenance::Person.to_s
    = render 'person_form', :form => form, :cancel_url => entities_path
  - elsif @entity.type == EntityMaintenance::Organization.to_s
    = render 'organization_form', :form => form, :cancel_url => entities_path

app/views/entity_maintenance/entities/index.html.haml
%h1 Listing people
= link_to 'New Person', new_entity_path(:type => EntityMaintenance::Person.to_s)

= render 'people'

%h1 Listing organizations
= link_to 'New Organization', new_entity_path(:type => EntityMaintenance::Organization.to_s)
= render 'organizations'

app/views/entity_maintenance/entities/new.html.haml
%h1 New #{@entity.type == EntityMaintenance::Person.to_s ? 'Person' : 'Organization'}

= simple_form_for @entity, :url => entities_path, :html => { :class => 'form' } do |form|
  - if @entity.type == EntityMaintenance::Person.to_s
    = render 'person_form', :form => form, :cancel_url => entities_path
  - elsif @entity.type == EntityMaintenance::Organization.to_s
    = render 'organization_form', :form => form, :cancel_url => entities_path

app/views/entity_maintenance/entities/show.html.haml
%p#notice
  = notice

- if @entity.class == EntityMaintenance::Person
  %dl
    %dt Name:
    %dd
      = @entity.full_name
- elsif @entity.class == EntityMaintenance::Organization
  %dl
    %dt Name:
    %dd
      = @entity.name
  %dl
    %dt Industry:
    %dd
      = @entity.industry

%dl
  %dt
    Contact Info:
    \|
    = link_to 'Add Contact Info', new_entity_contact_info_path(@entity)
  %dd
    = render 'entity_maintenance/contact_infos/table', :entity => @entity
%dl
  %dt
    Addresses
    \|
    = link_to 'Add Address', new_entity_address_path(@entity)
  %dd
    = render 'entity_maintenance/addresses/table', :entity => @entity


= link_to 'Edit', edit_entity_path(@entity)
\|
= link_to 'Destroy', entity_path(@entity), :method => :delete, :data => { :confirm => 'Are you sure?' }
\|
= link_to 'Back', entities_path

app/views/layouts/entity_maintenance/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EntityMaintenance</title>
  <%= stylesheet_link_tag    "entity_maintenance/application", media: "all" %>
  <%= javascript_include_tag "entity_maintenance/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>